### ISSUE TITLE
M4V support

### ISSUE THREAD

**Issue by grdw** [WeTransfer/format_parser#139]
Follow up from #138 

---

Currently in Spaceship we have a video thumbnailer. In Spaceship we check the file extension instead of actually using the format parser (mainly because changing the file extension on mobile is quite uncommon). However, we still have plans to use the format parser for this, if only it supported M4V formats.

Related: WeTransfer/spaceship#1975

**Comment by julik** [comment]
Isn't MV4 a subset of MPEG4 and thus effectively MOV? The parser we have should be picking it up.

**Comment by julik** [comment]
I.e. it should be supported via https://github.com/WeTransfer/format_parser/blob/master/lib/parsers/moov_parser.rb or it should be relatively within reach to make sure it is supported

**Comment by grdw** [comment]
> Isn't MV4 a subset of MPEG4 and thus effectively MOV?

I didn't knew this, but this is correct. It is like a MOV. I guess it requires some minor changes to the `likely_match?` method, to make sure the mov parser get's sorted on top of the list of parsers, but I guess that's it. It already should be supported indeed.
