### ISSUE TITLE
WAV parser

### ISSUE THREAD

**Issue by julik** [WeTransfer/format_parser#31]
for WAV sound files, providing information similar to the AIFF parser

**Comment by duplamatyi** [comment]
@julik I would like to start working on the WAV parser if possible. As WAV files sometimes might contain compression I would propose in a first step to implement the correct prying of the RIFF chunk, fmt chunk and the data chunk for WAV files where the format tag of the fmt chunk is 1(meaning no compression). Later maybe I could also include the case of WAV files with compression in my PR but maybe that could be a second PR as a future enhancement.

See:
https://web.archive.org/web/20080113195252/http://www.borg.com/~jglatt/tech/wave.htm
http://soundfile.sapp.org/doc/WaveFormat/

**Comment by julik** [comment]
@duplamatyi 👍  go ahead

**Comment by duplamatyi** [comment]
@julik Created [#PR 42](https://github.com/WeTransfer/format_parser/pull/42). After all I addressed both the standard PCM format and the non PCM format cases. The approach is really similar but slightly differs from the aiff_parser. Please let me know what you think.

**Comment by julik** [comment]
Aand we got one ❤️
