### ISSUE TITLE
MPEG4 (ISO) container parser

### ISSUE THREAD

**Issue by julik** [WeTransfer/format_parser#32]
We should see how much can be shared between the video and audio parts, and which box definitions we should support. There is a wonderful gem for this here https://github.com/zuku/bmff but I doubt we need _all_ of it - besides, I don't think we will need another dependency.

**Comment by bermannoah** [comment]
One reason we _might_ want to think about adding the dependency is that we'll probably want to use a BMFF parser for lots of different things - HEIF files, for example, [also use it](https://nokiatech.github.io/heif/technical.html) as a base container format. At least merits some testing!

**Comment by julik** [comment]
Can be, and we will indeed need it for stuff like .m4a audio from iTunes Store and the like. However, that gem is very likely to exceed our read limits - it reads all the boxes and builds an in-memory map of the stuff in the file, which is quite likely in our case to cause the entire file to be written. So at the very least we should figure out how to tell it to bail out early if we use it, otherwise `ReadLimiter` will kick in.

**Comment by julik** [comment]
The urge is big so I'll take this.

**Comment by julik** [comment]
Closing this since we have MOOV parser
