### ISSUE TITLE
CR2 Parser

### ISSUE THREAD

**Issue by bermannoah** [WeTransfer/format_parser#33]
CR2 files are essentially TIFF files with additional content shoved into the headers. We need a way of detecting that an incoming TIFF is actually a CR2, especially if we want to use image processing libraries like ImageMagick - which sometimes don't make the distinction. Because CR2 files also often contain a preview image, it could be interesting to try to withdraw and do something with the preview as well. Otherwise we want the same data that we retrieve for TIFFs: resolution and orientation.

 Documentation for the format can be found [at this site](http://lclevy.free.fr/cr2/#key_info), and you can click [here](http://www.rawsamples.ch/raws/canon/5d/RAW_CANON_5D_ARGB.CR2) to download a sample .CR2 file which is [licensed](http://rawsamples.ch/index.php/en/legal-stuff) under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) license.

**Comment by onurkucukkece** [comment]
Hi,

I would like to work on this issue.

**Comment by bermannoah** [comment]
Hi @onurkucukkece! Feel free to take it on. Let me know if I/we can help in any way, if you have any questions, etc. :)

**Comment by onurkucukkece** [comment]
As some old models such as the current CR2 file in fixtures (Canon EOS Rebel XT / 350D) does not contain either preview sizes or the orientation info in TIFF headers. Hence the parser checks the CanonAFInfo and CanonAFInfo2 tags for actual sizes. Or would you prefer it would parse the preview sizes where available?

For those mentioned models, orientation and image orientation values are returning nil.

Also image preview feature added for the CR2 files within reading limits

Additional CR2 files for specs are downloaded from 
http://www.rawsamples.ch/index.php/en/canon

Used references
http://lclevy.free.fr/cr2/
https://github.com/lclevy/libcraw2/blob/master/docs/cr2_poster.pdf
https://sno.phy.queensu.ca/~phil/exiftool/TagNames/Canon.html
http://sylvana.net/jpegcrop/exif_orientation.html

Please see my PR #67

**Comment by bermannoah** [comment]
😃 I added some comments to the PR, lets continue over there.

**Comment by bermannoah** [comment]
Closed in #67
