### ISSUE TITLE
PDF Parser

### ISSUE THREAD

**Issue by bermannoah** [WeTransfer/format_parser#35]
At the very utter total minimum we need to grab page count. From there we'll need additional information about those individual pages (as opposed to the document as a whole).

**Comment by westerg** [comment]
@bermannoah You can assign me for this issue. 

First up: I did some basic online reading on how to detect if a file is a PDF and found out that most PDF's (about ~99%) can be identified by scanning for the first 9 bytes where the format is: `%PDF-1.X` where X is a value between 0 to 7. Naturally there are edge cases. What's the usual approach for these edge cases (for example: ignore them, raise an error, ...)?

**Comment by bermannoah** [comment]
@westerg enjoy! :) At the moment we raise an error for these kinds of edge cases, though I guess it depends a little on the nature of the case itself. Start with the 99% that's standard and we can build from there? I'd rather the parser be able to retrieve the info we need - page count at the very _least_ - for the vast majority of things than spend a whole bunch of time on Super Rare PDF Format Used By One Designer In Taiwan But Only On Wednesdays.

**Comment by westerg** [comment]
I created a PR for a basic PDF parser. See [the PR](https://github.com/WeTransfer/format_parser/pull/71) for a bit more explanation. I'd love to hear your - or somebody else's - review on it. Thanks in advance for your time.
