### ISSUE TITLE
Error reading mp3 file (ID3V2)

### ISSUE THREAD

**Issue by roysab** [WeTransfer/format_parser#50]
When reading in an mp3 file I get the following error:
`RuntimeError: Expected to read 262245 bytes for ID3V2 frame COM, but got 177428`

You can replicate it by downloading the following zip which contains some mp3 files:
https://psychologyofdjing.wetransfer.com/downloads/01ef30567aa387a4df40f20f3e4d2de020171006090227/bc7cc0

You can use the `Cassy.mp3` file to replicate this issue.

**Comment by julik** [comment]
❤️

**Comment by julik** [comment]
Leaving the issue open for now because it's actually our ID3 parser that is playing up.

**Comment by julik** [comment]
leeeavign open, leeeaving open...

**Comment by bermannoah** [comment]
Whoops. Sorry.

**Comment by julik** [comment]
I've made a start at fixing this in #115 but could use some help since time is limited. Tagging as good first issue. Maybe we should do the same we did with EXIFR here and just use a damn gem :-)

**Comment by julik** [comment]
I think this is fixed in #115 @roysab feel free to reopen if we encounter issues again
