### ISSUE TITLE
Some JPEG files cause reads too far into the file - and go over the maximum reads restriction

### ISSUE THREAD

**Issue by bermannoah** [WeTransfer/format_parser#75]
We've found a few files (mostly Photoshop-generated CMYK jpegs) that have characters that we can't read - or read incorrectly - and this can lead to mildly unbounded reads, or it'll bail with a result of `nil`. Creating an issue to track research etc.

**Comment by julik** [comment]
So far it seems the issue is rather that we _can_ parse those files, but we have to read a lot of data to get to the chunks which contain dimensions.

**Comment by julik** [comment]
I've upped the page size a bit, closing for now - let's see if it reemerges. Tentatively fixed in #89
