### ISSUE TITLE
.docx files are sometimes read as MP3s

### ISSUE THREAD

**Issue by bermannoah** [WeTransfer/format_parser#82]
We've seen .docx files being parsed and returning `:previewable=>true, :preview_metadata=>{:duration_in_seconds=>"728.97306"}` which is curious and undesirable. Sample file in comments.

**Comment by bermannoah** [comment]
[Here](https://we.tl/3R6yNOxJu8) is the sample file that caused this issue, used here with the permission of the owner.

**Comment by julik** [comment]
I've added a check for the ZIP local entry signature at the start of the file to try and avoid this - the MP3 parser has to be pretty liberal due to the way MP3 files are structured.
