### ISSUE TITLE
ZIP Parser will sometimes get caught in an infinite loop 

### ISSUE THREAD

**Issue by bermannoah** [WeTransfer/format_parser#87]
See the comments [here](https://github.com/WeTransfer/format_parser/pull/83/files/984e74cd3c544c5ebb2eae9a85fcc7b06dffaf89..06469ccfb7521784493f59b6894458fb58ffedb8#diff-ae0081f893f5ab2a5e6df64e3e55154bR363) - sometimes the ZIP parser gets a bit confused by the fuzz specs and either never stops reading into the file or takes an excessively long time to realise it's not dealing with a ZIP.

**Comment by julik** [comment]
It's not an infinite loop - it is a worst case performance situation. I.e. the tests were passing but they took 1 minute and 45 seconds just for all the fuzzed results. Addressed in #88
